### ISSUE TITLE
The times returned by the endpoints are not normalized to GMT

### ISSUE THREAD

**Issue by admoca60** [mirkosertic/flight-recorder-starter#11]
When I invoke the endpoint to list the recordings, the time are not normalized to GMT or similar, but it's an Instance java object that doesn't have any mark regarding the time zone used. We should be aware that internal JFR api works with Instance and the cleanUp scheduled job uses these fields to work.

**Comment by mirkosertic** [comment]
Fix merged to master. Thank you for your contribution!

**Comment by admoca60** [comment]
Ok perfect! We can close this issue. Do you do it?

**Comment by admoca60** [comment]
This is done!
