### ISSUE TITLE
Separate in two different controller the static resources and actuator operations

### ISSUE THREAD

**Issue by admoca60** [mirkosertic/flight-recorder-starter#9]
Currently, the "FlightRecorderEndpoint.java" file contains both the actuator operations and methods to get static resources.

It could be a great idea if we can separate them. I can help you if you are interested.

Basically, the solution is to create a RestController just in the management context.

**Comment by mirkosertic** [comment]
Fix merged to master. Thank you for your contribution!

**Comment by admoca60** [comment]
Ok perfect! We can close this issue. Do you do it?

**Comment by admoca60** [comment]
This is done!
